### PR TITLE
fix flask-smorest quoting

### PR DESCRIPTION
**Pull request by bodik**
fix flask-smorest quoting

### CODE REVIEW

**Comment by bodik** [comment]
a little trick for quoting which fixes flas-smorest extension workflow

**Comment by greyli** [comment]
You can use quote to escape quote: https://github.com/greyli/flask-extension-status/blob/main/extensions.yml#L64

**Comment by bodik** [comment]
> You can use quote to escape quote: https://github.com/greyli/flask-extension-status/blob/main/extensions.yml#L64

Does not seem so, I've been there yesterday
https://github.com/greyli/flask-extension-status/actions/runs/7029417573/workflow

**Comment by greyli** [comment]
It turns out we should add the "|" to the command to make sure the whole line can be read as a complete string. https://github.com/greyli/flask-extension-status/pull/9/files#diff-73ed4e9979da612f5b529fdca94a62445696b9eb6195b2705199114983957f30R28

**Pull request closed without merging**
